apiVersion: v1
kind: Secret
metadata:
  name: notes-secrets
  namespace: notes-app
type: Opaque
stringData:
  DB_NAME: "notes_db"
  DB_USER: "postgres"
  DB_PASSWORD: "SecurePassword123!"
  RECAPTCHA_SECRET_KEY: "6Ld1uiAsAAAAAJbHNyBKZZGO8RT2o9zTWaO7S4K2"
